apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nameOverride }}-config
data:
  RABBITMQ_UNAME: "guest"
  RABBITMQ_PASS:  "guest"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "{{ .Values.rabbitmq.service.port }}"
  REDIS_HOST: "redis"
  REDIS_PORT: "{{ .Values.redis.service.port }}"
  REDIS_PASSWORD: "{{ .Values.redis.password }}"
  QUEUE_NAME: "test-job-queue"
  JWT_SECRET: "YOU_LIVE_ONLY_ONCE"
