apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameOverride }}-rabbitmq
spec:
  replicas: {{ .Values.rabbitmq.replicaCount }}
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "{{ .Values.rabbitmq.image }}"
          ports:
            - containerPort: {{ .Values.rabbitmq.service.port }}
