apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: {{ .Values.nameOverride }}
